version: '3.8'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.2.4
    container_name: zoo1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    networks:
      - kafka-net
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.2.4
    container_name: kafka1
    hostname: kafka1
    depends_on:
      - zoo1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "29092:29092"

  kafka2:
    image: confluentinc/cp-kafka:7.2.4
    container_name: kafka2
    hostname: kafka2
    depends_on:
      - zoo1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    networks:
      - kafka-net
    ports:
      - "9093:9093"
      - "29093:29093"
  
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.2.4
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:19093
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - kafka-net
    depends_on:
      - zoo1
      - kafka1
      - kafka2

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.4
    container_name: control-center
    depends_on:
      - zoo1
      - kafka1
      - kafka2
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zoo1:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 2
      PORT: 9021
      CONTROL_CENTER_ID: "MY_C3"
    networks:
      - kafka-net
    ports:
      - 9021:9021
networks:
  kafka-net:
    name : kafka-net
    driver: bridge